app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from os import path
from cfg import Config
from flask_session import Session


sess = Session()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'



def create_app():
    app = Flask(__name__)
    app.debug = True
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)
    sess.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .users import users as users_blueprint
    app.register_blueprint(users_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)


from . import views

app/main/views.py
from flask import render_template
from . import main

@main.route('/main', methods=['POST', 'GET'])
def dashboard():
    return render_template("Dashboard.html")

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

app/users/views.py
from flask import render_template
from . import users

@users.route('/users', methods=['POST', 'GET'])
def userviews():
    return render_template('users/users.html')

app/templates/Dashboard.html
{% extends "layout.html" %}

{% block content %}
<div class="row row-box">
    <div class="col-sm-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-success pull-right">Users</span>
                <h5>用户总数</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins"><a href="#">1</a></h1>
                <small>All user</small>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-info pull-right">Servers</span>
                <h5>服务器总数</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins"><a href="#">3</a></h1>
                <small>All servers</small>
            </div>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-primary pull-right">online</span>
                <h5>在线用户</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins"><a href="#"> <span id="online_users">1</span></a></h1>
                <small>Online user</small>
            </div>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-ok pull-right">WorkOrders</span>
                <h5>工单总数</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins"><a href="#"> <span id="online_hosts">0</span></a></h1>
                <small>Connected host</small>
            </div>
        </div>
    </div>
</div>
</div>
{% block Launch %}
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">
    添加服务器
</button>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">New message</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Recipient:</label>
                        <input type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label">Message:</label>
                        <textarea class="form-control" id="message-text"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send message</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/discards/descard_info.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{url_for('static',filename='css/dashboard.css')}}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file"></span>
                  Orders
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="users"></span>
                  Customers
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reports
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  Integrations
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>

          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

          <h2>Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>

app/templates/footer.html
<div class="clearfix"></div>
<footer>
    <div class="container-fluid">
        <p class="copyright">Copyright @ 2018-11-15 Xuzhiwei & Wangshuaiwen Version1.0 <a href="http://buchimgu.cn/" target="_blank" title="buchimogu">我的主页</a></p>

    </div>
</footer>

app/templates/layout.html
<!doctype html>
<html lang="en">

<head>
	<title>Orange</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{{url_for('static',filename='assets/css/layout.css')}}">
	<link rel="stylesheet" href="../static/assets/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="../static/assets/vendor/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="../static/assets/vendor/linearicons/style.css">
	<link rel="stylesheet" href="../static/assets/vendor/chartist/css/chartist-custom.css">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="../static/assets/css/main.css">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="../static/assets/css/demo.css">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="../static/assets/img/apple-icon.png">
	<link href="{{ url_for('static',filename='image/juzi.ico') }}" type="image/x-icon" rel="icon">
	<link rel="stylesheet" href="{{url_for('static',filename='assets/css/myweb.css')}}">
	<!--<link rel="icon" type="image/png" href="{{ url_for('static', filename='image/橘子b.png')}}">-->
</head>
{% block stylesheet %}
{% endblock %}


<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		{% include 'nav.html' %}
		<div class="main">
			<div class="container-fluid">
				{% include 'nav_bar_header.html' %}
				<div class="wrapper wrapper-content">
				{% block content %}{% endblock %}
				</div>
			</div>
		</div>
		{% include 'footer.html' %}
	</div>
	<!-- END WRAPPER -->
	{% include 'script_js.html' %}
	{% block script %}
	{% endblock %}
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ORANGE运维平台</title>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='assets/css/style.css') }}">
    <!--<link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='assets/css/bootstrap.min.css') }}">-->
    <script src="{{ url_for('static',filename='assets/scripts/main.js') }}"></script>
    <link href="{{ url_for('static',filename='assets/img/juzi.ico') }}" type="image/x-icon" rel="icon">
</head>
<body>
    {% if error_pass %}<div class="alert alert-success" role="alert">{{ error_pass }}</div>{% endif %}
    <div id="container" class="divqj">
      <div class="div1">
        <div class="divtp">
          <img src="{{ url_for('static', filename='assets/img/橘子b.png')}}">
        </div>
        <form method="post">
        <div class="div2">
          <h3>Please enter username and password</h3>
          <input type="text" placeholder="Username" name="username" id="yyy">
        </div>
        <div class="div3">
          <input type="password" placeholder="Password" name="password" id="mmm">
        </div>
        <div class="divdibu">
          <input type="submit" value="login" id="tj" onclick="Pd()">
        </div>
        </form>
      </div>
      <div class="bqxx">
      <p >Copyright @ 2018-11-15 Xuzhiwei & Wangshuaiwen Version1.1</p>
      </div>
    </div>
</body>
</html>

app/templates/nav.html
{% if session.role_id == 1 %}
<!-- LEFT SIDEBAR -->
<div id="sidebar-nav" class="sidebar">
    <div class="sidebar-scroll">
        <nav>
            <ul class="nav">
                <li><a href="{{ url_for('main.dashboard')}}" class="active"><i class="lnr lnr-home"></i> <span>仪表盘</span></a></li>
                <li><a href="{{ url_for('users.userviews')}}" class=""><i class="lnr lnr-dice"></i> <span>用户管理</span></a></li>
                <li><a href="#" class=""><i class="lnr lnr-chart-bars"></i> <span>数据备份</span></a></li>
                <li><a href="#" class=""><i class="lnr lnr-cog"></i> <span>服务器列表</span></a></li>
                <li><a href="#" class=""><i class="lnr lnr-alarm"></i> <span>计划任务</span></a></li>
                <li>
                    <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>工单</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                    <div id="subPages" class="collapse ">
                        <ul class="nav">
                            <li><a href="#" class="">工单统计</a></li>
                            <li><a href="#" class="">工单列表</a></li>
                            <li><a href="#" class="">我的工单</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="#" class=""><i class="lnr lnr-code"></i> <span></span>执行操作</a></li>
                <!--<li><a href="#" class=""><i class="lnr lnr-text-format"></i> <span>Typography</span></a></li>-->
                <!--<li><a href="#" class=""><i class="lnr lnr-linearicons"></i> <span>Icons</span></a></li>-->
            </ul>
        </nav>
    </div>
</div>
<!-- END LEFT SIDEBAR -->
{% endif%}

app/templates/nav_bar_header.html
<!-- NAVBAR -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="brand">
        <a href="{{ url_for('main.dashboard')}}"><img src="../static/assets/img/juzilogo1.png" alt="Klorofil Logo" class="img-responsive logo"></a>
    </div>
    <div class="container-fluid">
        <div class="navbar-btn">
            <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
        </div>
        <form class="navbar-form navbar-left">
            <div class="input-group">
                <input type="text" value="" class="form-control" placeholder="搜索...">
                <span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
            </div>
        </form>
        <div class="navbar-btn navbar-btn-right">
            <a class="btn btn-success update-pro" href="{{ url_for('auth.logout') }}" title="Upgrade to Pro"><i class="fa fa-rocket"></i> <span>注销</span></a>
        </div>
        <div id="navbar-menu">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                        <i class="lnr lnr-alarm"></i>
                        <span class="badge bg-danger">5</span>
                    </a>
                    <ul class="dropdown-menu notifications">
                        <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
                        <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
                        <li><a href="#" class="more">See all notifications</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>帮助</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Basic Use</a></li>
                        <li><a href="#">Working With Data</a></li>
                        <li><a href="#">Security</a></li>
                        <li><a href="#">Troubleshooting</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="../static/assets/img/user.png" class="img-circle" alt="Avatar"> <span>{{ session.get('username') |capitalize}}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
                        <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                        <li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                        <li><a href="{{ url_for('auth.logout') }}"><i class="lnr lnr-exit"></i> <span>注销</span></a></li>
                    </ul>
                </li>
                <!-- <li>
                    <a class="update-pro" href="#downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
                </li> -->
            </ul>
        </div>
    </div>
</nav>
<!-- END NAVBAR -->

app/templates/script_js.html
<!-- Javascript -->
<script src="../static/assets/vendor/jquery/jquery.min.js"></script>
<script src="../static/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../static/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="../static/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../static/assets/vendor/chartist/js/chartist.min.js"></script>
<script src="../static/assets/scripts/klorofil-common.js"></script>
<script>
    $(function() {
        var data, options;

        // headline charts
        data = {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            series: [
                [23, 29, 24, 40, 25, 24, 35],
                [14, 25, 18, 34, 29, 38, 44],
            ]
        };

        options = {
            height: 300,
            showArea: true,
            showLine: false,
            showPoint: false,
            fullWidth: true,
            axisX: {
                showGrid: false
            },
            lineSmooth: false,
        };

        new Chartist.Line('#headline-chart', data, options);


        // visits trend charts
        data = {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            series: [{
                name: 'series-real',
                data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
            }, {
                name: 'series-projection',
                data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
            }]
        };

        options = {
            fullWidth: true,
            lineSmooth: false,
            height: "270px",
            low: 0,
            high: 'auto',
            series: {
                'series-projection': {
                    showArea: true,
                    showPoint: false,
                    showLine: false
                },
            },
            axisX: {
                showGrid: false,

            },
            axisY: {
                showGrid: false,
                onlyInteger: true,
                offset: 0,
            },
            chartPadding: {
                left: 20,
                right: 20
            }
        };

        new Chartist.Line('#visits-trends-chart', data, options);


        // visits chart
        data = {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            series: [
                [6384, 6342, 5437, 2764, 3958, 5068, 7654]
            ]
        };

        options = {
            height: 300,
            axisX: {
                showGrid: false
            },
        };

        new Chartist.Bar('#visits-chart', data, options);


        // real-time pie chart
        var sysLoad = $('#system-load').easyPieChart({
            size: 130,
            barColor: function(percent) {
                return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
            },
            trackColor: 'rgba(245, 245, 245, 0.8)',
            scaleColor: false,
            lineWidth: 5,
            lineCap: "square",
            animate: 800
        });

        var updateInterval = 3000; // in milliseconds

        setInterval(function() {
            var randomVal;
            randomVal = getRandomInt(0, 100);

            sysLoad.data('easyPieChart').update(randomVal);
            sysLoad.find('.percent').text(randomVal);
        }, updateInterval);

        function getRandomInt(min, max) {
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }

    });
</script>

app/templates/users/users.html
{% extends "layout.html" %}

{% block content %}
<div class="panel">
    <div class="panel-body">
        <p class="users-bottom">
            <button type="button" class="btn btn-success pull-right">添加用户</button>
        </p>
        <table class="table-myset table table-bordered">
            <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Created_time</th>
                <th>UserRole</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>tomas</td>
                <td>tomas@lemon.com</td>
                <td>2018-11-15 17:59:15</td>
                <td>Administrator</td>
                <td>
                    <button type="button" class="btn btn-info btn-xs">
                        <i class="fa fa-pencil-square-o"></i>
                    </button>
                    <button type="button" class="btn btn-info btn-xs">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </button>
                    <button type="button" class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </td>
            </tr>
            <tr>
                <td>gaga</td>
                <td>gaga@lemon.com</td>
                <td>2016-07-01 16:42:14</td>
                <td>Develop</td>
                <td>                    <button type="button" class="btn btn-info btn-xs">
                    <i class="fa fa-pencil-square-o"></i>
                </button>
                    <button type="button" class="btn btn-info btn-xs">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </button>
                    <button type="button" class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </td>
            </tr>
            <tr>
                <td>lala</td>
                <td>lala@lemon.com</td>
                <td>2016-07-01 17:58:10</td>
                <td>User</td>
                <td>                    <button type="button" class="btn btn-info btn-xs">
                    <i class="fa fa-pencil-square-o"></i>
                </button>
                    <button type="button" class="btn btn-info btn-xs">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </button>
                    <button type="button" class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="panel">
    <div class=" panel-body padding-myset">
        <table class="zero-margin table table-bordered">
            <thead>
            <tr>
                <th>Role_name</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Administrator</td>
            </tr>
            <tr>
                <td>Develop</td>
            </tr>
            <tr>
                <td>Guest</td>
            </tr>
            <tr>
                <td>User</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}